# -*- mode: org; -*-
#+TITLE: README
#+DESCRIPTION:
#+KEYWORDS:
#+AUTHOR:
#+email:
#+INFOJS_OPT:
#+STARTUP:  content

#+DATE: CREATED: <Tue Mar 14 19:24:48 MSK 2023>
# Time-stamp: <Последнее обновление -- Wednesday March 15 11:26:45 MSK 2023>

* Кастомные чекбоксы с использованием обычных встроенных решений

  К этому разделу относятся файлы:
  - images.html
  - inline.html
  - inline2.html
  - hidden.html
  - styles.html

  Чекбоксы оформлялись с помощью [[https://www.youtube.com/@pepelsbey][Вадима Макеева]].

  [[https://www.youtube.com/watch?v=E6kLaaQFctU][Кастомные чекбоксы правильно]].

  В файле *images.html* оформление сделано при помощи картинок.

  В *inline.html* иконки *svg* переведены в инлайновые элементы при помощи сервиса
  [[https://yoksel.github.io/url-encoder/ru/][URL-encoder для SVG]].

  В *styles.html* всё то же самое, за исключением «галки» отметки, оформлено стилями.

  Но в трёх предыдущих оформлениях есть недостаток - в IE-11 всё ломается, поэтому можно
  использовать оформление из файла *hidden.html*. Здесь оригинальным элементам *.check__input*
  даны минимальная ширина и высота (по 1px), применено свойство *overflow: hidden;*, и на всякий
  случай *clip: rect(0 0 0 0);*.

  Пример кода для того, чтобы что-то спрятать. Это только пример!
  Это самый совместимый со всеми браузерами способ.

  #+BEGIN_EXAMPLE
.visually__hidden {
    position: absolute;
    width: 1px;
    height: 1px;
    margin-left: -1px;
    border: 0;
    padding: 0;
    overflow: hidden;
    clip: rect(0 0 0 0);
}
  #+END_EXAMPLE

  В файле *inline2.html* чекбоксы вставлены прямо при помощи тегов *<svg>*, но для данного
  оформления этого лучше не делать, смысла нет.
