# -*- mode: org; -*-
#+TITLE: README
#+DESCRIPTION:
#+KEYWORDS:
#+AUTHOR:
#+email:
#+INFOJS_OPT:
#+STARTUP:  content

#+DATE: CREATED: <Fri Mar 24 22:35:33 MSK 2023>
# Time-stamp: <Последнее обновление -- Saturday March 25 0:33:56 MSK 2023>

Образец макета взят у [[https://www.youtube.com/@ivashov/featured][Анатолия Ивашова]], он  рассказывал о нём в видео
[[https://www.youtube.com/watch?v=wmaIWvWwX3c][Никто не знает об этом способе верстки! html & css]].

Как всегда макет немного переделан, но исходный образец лежит в архиве (на всякий случай).

Идея Анатолия заключается в очистке *html* от лишнего кода, в частности от лишних контейнеров.

В общем-то довольно интересно мне кажется, но я не показатель, я любитель, возможно профессионалы
найдут в этом кучу недостатков.

** По поводу моих исправлений

   - Общего блока *container* изначально не было и я его добавил, дабы прибить футер к низу, где ему,
     по мнению большинства, самое место. Способ прибития был подсмотрен у [[https://www.youtube.com/@FreelancerLifeStyle][Жени Андриканич]] в
     short-видео [[https://www.youtube.com/shorts/kNGYuTelE3E][Как прижать футер к низу страницы HTML CSS FLEX / Фрилансер по жизни / #Shorts]].
     Футер также добавлен мной, в образце Анатолия он отсутствует;

   - Оригинальный (изначальный) блок стилей *body* я закомментировал. Там были использованы

   #+begin_src css

   display: grid;
   grid-template-rows: 80px;

   #+end_src

   за счёт строки (*rows*) была создана высота *header* 80px, но после использования мной общего
   контейнера эти стили перестали срабатывать.

   - К блоку *header* у автора были применены стили

     #+begin_src css
     padding: 0 calc(50% - var(--contentWidth) / 2);
     #+end_src

     а к блоку с оригинальным классом *block* у него же (Ивашова) добавлен стиль

     #+begin_src css
     margin: 0 calc(50% - var(--contentWidth) / 2);
     #+end_src

     в результате чего общий вид стал вот таким:

     [[alt text][https://github.com/abunbux/templates/blob/main/layout/layout_without_container/README_img/Screenshot_20230324_234608.png]]

     То есть, простым языком: за счёт стиля *padding* к *header* шапка осталась длинною во всю страницу,
     но сами элементы шапки (логотип, меню, форма входа) как бы помещены в те же рамки, что и
     основной контент, располагаемый в блоке *block*.

     Ну а за счёт стиля *margin* к *block* и создан тот самый ограничивающий контейнер.

     Я на 0.5 изменил *padding* у *header* (можно и больше, или чуть меньше)

     #+begin_src css
     padding: 0 calc(50% - var(--contentWidth) / 2.5);
     #+end_src

     Вот результат:

      [[alt text][https://github.com/abunbux/templates/blob/main/layout/layout_without_container/README_img/Screenshot_20230325_002606.png]]

** Будучи в здравом уме и твёрдой памяти

   я прекрасно понимаю, что Анатолий набросал этот образец, чтобы продемонстрировать нам идею, я её
   понял, ну а дальше буду кромсать код и добавлять свой для тренировки.
